imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

swiftmailer:
    delivery_address: me@example.com

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options: []
        
        
doctrine:
    dbal:
        driver:   "%database_staging_driver%"
        host:     "%database_staging_host%"
        port:     "%database_staging_port%"
        dbname:   "%database_staging_name%"
        user:     "%database_staging_user%"
        password: "%database_staging_password%"